networks:
  hobbing-network:
    driver: bridge

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - SPRING_REDIS_HOST=/path/to/redis.conf
      - SPRING_REDIS_PORT=6379
    networks:
      - hobbing-network


  eureka-server:
    build:
      context: ./
      dockerfile: com.hobbing.eurekaserver/Dockerfile
    image: eureka-server:latest
    ports:
      - "19000:19000"
    depends_on:
      - redis
    networks:
      - hobbing-network

#  coupon:
#    build:
#      context: ./com.hobbing.coupon
#    image: coupon
#    ports:
#      - "19000:19040"
#    depends_on:
#      - eurekaserver
#    networks:
#      - hobbing-network

  gateway:
    build:
      context: ./
      dockerfile: com.hobbing.gateway/Dockerfile
    image: gateway:latest
    ports:
      - "19006:19006"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://hobbing-eureka:19000/eureka/
    networks:
      - hobbing-network

  proxy-gateway:
    build:
      context: ./
      dockerfile: com.hobbing.proxygateway/Dockerfile
    image: proxy-gateway:latest
    ports:
      - "19005:19005"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://hobbing-eureka:19000/eureka/
    networks:
      - hobbing-network

#  reservation-pay:
#    build:
#      context: ./com.hobbing.reservation-pay
#    image: reservation-pay
#    ports:
#      - "19000:19050"
#    depends_on:
#      - eurekaserver
#    networks:
#      - hobbing-network

  user:
    build:
      context: ./
      dockerfile: com.hobbing.user/Dockerfile
    image: user:latest
    ports:
      - "19020:19020"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://hobbing-eureka:19000/eureka/
    networks:
      - hobbing-network

#  lecture:
#    build:
#      context: ./com.hobbing.lecture
#    image: lecture
#    ports:exit

#      - "19000:19030"
#    depends_on:
#      - eurekaserver
#    networks:
#      - hobbing-network


