spring.application.name=coupon

# PostgreSQL RDS ?????? ?? ??
spring.datasource.url=jdbc:postgresql://database-8.crm4w6m8w3t1.ap-northeast-2.rds.amazonaws.com:5432/coupon
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Tmvkfmxk123

# JPA ??
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ?? ??
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
