server:
  port: 19000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://hobbing-eureka:19000/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 120000
  instance:
#    hostname: hobbing-elb-1223327969.ap-northeast-2.elb.amazonaws.com
    hostname: hobbing-eureka
#    metadata-map:
#      region: ap-northeast-2