spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lecture_db
    username: lecture
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: dev
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
