server:
  port: 19005

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/auths/**

        - id: gateway
          uri: lb://gateway
          predicates:
            - Path=/**

      discovery:
        locator:
          enabled: true

    loadbalancer:
      cache:
        enabled: true

#  cache:
#    type: caffeine
#    cache-names:
#      - loadbalancer
#    caffeine:
#      spec: maximumSize=500,expireAfterAccess=300s

  config:
    import: classpath:application-key.yml
    
eureka:
  client:
    service-url:
      defaultZone: http://169.254.172.2:eureka-server:19000/eureka/
#    fetch-registry: true
#    register-with-eureka: true
  instance:
    lease-renewal-interval-in-seconds: 30  # heartbeat 주기
    lease-expiration-duration-in-seconds: 60  # 만료 시간
#    initial-status: UP
#    metadata-map:
#      region: ap-northeast-2

service:
  jwt:
    secret-key: ${SECRET-KEY}
    access-expiration: 1800000 # 30분
  internal:
    internal-key: ${INTERNAL-KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"

