server:
  port: 19006

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**
          filters:
            - name: UserAuthorizationFilter

        - id: lecture
          uri: lb://lecture
          predicates:
            - Path=/lectures/**, /waitinglist/**
          filters:
            - name: LectureAuthorizationFilter

        - id: coupon
          uri: lb://coupon
          predicates:
            - Path=/coupons/**, /users/me/coupons
          filters:
            - name: CouponAuthorizationFilter

        - id: reservation
          uri: lb://reservation
          predicates:
            - Path=/reservations/**, /payments/**, settlements/**
          filters:
            - name: ReservationAuthorizationFilter

      discovery:
        locator:
          enabled: true

  config:
    import: classpath:application-key.yml

eureka:
  client:
    service-url:
      defaultZone: http://hobbing-elb-1223327969.ap-northeast-2.elb.amazonaws.com/eureka/
  instance:
    initial-status: UP
    lease-renewal-interval-in-seconds: 60  # heartbeat 주기
    lease-expiration-duration-in-seconds: 180  # 만료 시간
    metadata-map:
      region: ap-northeast-2

management:
  endpoints:
    web:
      exposure:
        include: "*"

service:
  internal:
    internal-key: ${INTERNAL-KEY}